name: Publish to NPM

# read-only repo token
# no access to secrets
on:
  push:
    branches:
      - master
    paths-ignore:
      - '!.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ env.ENABLE_NPM_PUBLISH == 'true' }}
        with:
          strategy: upgrade
