name: Publish to NPM

# read-only repo token
# no access to secrets
on:
  push:
    branches:
      - master
    paths-ignore:
      - '!.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ env.NPM_TOKEN != '' }}
        with:
          token: ${{ env.NPM_TOKEN }}
          greater-version-only: true
